// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktzozcznjokemxmccfax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0em96Y3puam9rZW14bWNjZmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODMzOTksImV4cCI6MjA2Nzg1OTM5OX0.-Sq7t-kwsniTZXuFsIOKGa5joMRz-0IF1h-yQM8ReGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});